server.port= 8084

spring.datasource.url=jdbc:mysql://localhost:3306/micro3_auth
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

secrete-key= sdyugefgyuegvhuihweuir4yt8uhergr8hgjnerghuiyh8e54gtvkrivgj
expiration-time= 86400000
